### ISSUE TITLE
How to use KITTI Odometry 00-08 to train pose-exp-net？

### ISSUE THREAD

**Issue by yangbinchao** [ClementPinard/SfmLearner-Pytorch#107]
Hello, thank you for open-source this code. I am training the network recently, but I don't know how to train the pose estimation network, which requires KITTI Odometry 00-08. Looking forward to your reply.

**Comment by ClementPinard** [comment]
pose estimation and depth are trained at the same time.
If you want  to train on KITTI odometry 00-08 so that you don't have overfitting on the 09-10 scenes, I have not designed a data prepare script for other than raw dataset. You might either : identify the Odometry 09-10 scenes and dismiss them in the raw dataset, or use the data prepare script used by original author : https://github.com/tinghuiz/SfMLearner/blob/master/data/kitti/kitti_odom_loader.py
