### ISSUE TITLE
input three same images, out poses are not same  

### ISSUE THREAD

**Issue by wataincdx** [ClementPinard/SfmLearner-Pytorch#118]
when i in input three same images on pretrained model,  out poses are not same

**Comment by ClementPinard** [comment]
What is the exact output pose ? It is expected that the network is biased against the training set. More specifically, here the KITTI image are always going forward. So the network will have a tendency to output poses that translate to a forward motion even if there is no visible movement.
However if the outputted translation is small enough, i think it's not too much of a problem. Do you have a vizualisation of the warped images ? The network has been trained so that warped images ressemble the middle one. As such, here the real problem would be if the depth + pose did output a noticeable optical flow for warping the image.
