### ISSUE TITLE
raw kitti loader's calibration reader might be wrong

### ISSUE THREAD

**Issue by anuragranj** [ClementPinard/SfmLearner-Pytorch#12]
The cam.txt generated by processing the kitti_raw_loader are always (0,0,0,0,0,0,0,0,1). This doesn't make sense. I think fx,fy should be 1 instead of zero. Is it because of lines 102-103 in the kitti_raw_loader.py that sets them to zero? When I run the code zoom_x and zoom_y are always 0.
```
P_rect[0] *= zoom_x
P_rect[1] *= zoom_y

**Comment by ClementPinard** [comment]
https://github.com/ClementPinard/SfmLearner-Pytorch/issues/11

see here to solve the problem. Basically, it's a problem with pythonb 2.7.
Can you try with python3 ? Solving the problem for both python would be better, but this work has not been done yet.

**Comment by anuragranj** [comment]
Yes. It's the issue with python2.7.

**Comment by ClementPinard** [comment]
Faulty line is here : https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/data/kitti_raw_loader.py#L111

dividing is messed up in python2 ¯\\\_(ツ)_/¯
you could import `__futur__` as a classic tweak of python2 to get proper division, but as I ran all my tests using python3, it is strongly advised that you use it as well, since some other thin differences like this one can have big consequences without being easily spottable.

**Comment by anuragranj** [comment]
Sure. Thanks
