### ISSUE TITLE
about the pose scale

### ISSUE THREAD

**Issue by everythoughthelps** [ClementPinard/SfmLearner-Pytorch#154]
I run sfmlearner on tanks dataset, the visualization of depth estimation looks reasonable.
gt:
![image](https://github.com/ClementPinard/SfmLearner-Pytorch/assets/50064488/ca0f46c3-f21d-4ec7-9a52-2014068d6ba2)
pred:
![image](https://github.com/ClementPinard/SfmLearner-Pytorch/assets/50064488/78960b9f-4837-40e6-9a25-185986dd55d6)
However, the pose doesn't look good:
pred:  120 poses, 0.241m path length
gt:  120 poses, 13.809m path length

**Comment by ClementPinard** [comment]
The scale is not guaranteed. That's why the script to test pose is rescaling the path.

If you really want want to have absolute path length, you need a real world anchor. Either the depth (multiply the path length by the ratio between predicted depth and groundtruth depth) or the path itself, and the evaluation will just be about relative error

There is intrinsically a ambiguity regarding scale factor because you cannot know if you are looking at a small scale replica with small camera displacement or a full scale one with regular camera displacement, everything looks exactly the same.

**Comment by everythoughthelps** [comment]
Thank you for your response!
