### ISSUE TITLE
Motion between consecutive frames

### ISSUE THREAD

**Issue by guyrose3** [ClementPinard/SfmLearner-Pytorch#25]
In the readme you state enough motion is guaranteed between following frames.
I wonder how that affects the performance when the vehicle is static.
Can you elaborate on that design decision?
is it convergence issues?

Thanks,
Guy

**Comment by ClementPinard** [comment]
Hi, the motion between frames is important because otherwise the photometric error is 0 for any kind of depth as long as movement is 0. As a consequence, if you have too many static frames, you can end up having a pose estimator always outputting identity pose, and your depth will diverge.

This is just theoritical, and you can test on a dataset with static frames but I think KITTI has too many of them, and they are even not static scenes (with moving objects). Why the author discarded the static frames in the first place is probably because he got better resuts without than with.
