### ISSUE TITLE
stacked and sequence data loaders

### ISSUE THREAD

**Issue by canorbal** [ClementPinard/SfmLearner-Pytorch#26]
Hi!

1) Could you please explain the difference between SequenceFolder class from sequence_folders.py and from stacked_sequence_folders.py more precisely?

2) Also I didn't understand how get data in directory in this format:

`
    A sequence data loader where the images are arranged in this way:

        root/scene_1/0000000.jpg

        root/scene_1/0000000_cam.txt

        root/scene_1/0000001.jpg

        root/scene_1/0000001_cam.txt

        .
        root/scene_2/0000000.jpg

        root/scene_2/0000000_cam.txt
  `

I think your script data/prepare_train_data.py doesn't provide any opportunity to configure KITTI dataset in this format.

Thanks!

**Comment by ClementPinard** [comment]
Hello,
the stacked_sequence_folder is legacy from original tensorflow implementation. You can find it [here](https://github.com/tinghuiz/SfMLearner/blob/master/data/prepare_train_data.py)

The parsed datasets are slightly different, since Tinghuiz is using a list of static frames, while here we determine them with speed metadata.

I advise you to use the sequence_folder, which is much more flexible, and compact, but you can use stacked_seuence_folder if you want to get the exact same results as the paper's author's implementation

**Comment by canorbal** [comment]
Ok, thanks!
