### ISSUE TITLE
Equal number of batches expected at THCTensorMathBlas.cu:471

### ISSUE THREAD

**Issue by marianlonga** [ClementPinard/SfmLearner-Pytorch#27]
Hi, I'm trying to train using a non-KITTI dataset and keep getting this error about equal number of batches (note that I have modified the code so the line numbers aren't very relevant):

> Traceback (most recent call last):
  File "train.py", line 568, in <module>
    main()
  File "train.py", line 246, in main
    train_loss = train(args, train_loader, disp_net, pose_exp_net, optimizer, args.epoch_size, logger, training_writer, ...)
  File "train.py", line 336, in train
    args.rotation_mode, args.padding_mode)
  File "/.../loss_functions.py", line 44, in photometric_reconstruction_loss
    loss += one_scale(d, mask)
  File "/.../loss_functions.py", line 25, in one_scale
    ref_img_warped = inverse_warp(ref_img, depth[:,0], current_pose, intrinsics_scaled, intrinsics_scaled_inv, rotation_mode, padding_mode)
  File "/.../inverse_warp.py", line 183, in inverse_warp
    cam_coords = pixel2cam(depth, intrinsics_inv)  # [B,3,H,W]
  File "/.../inverse_warp.py", line 39, in pixel2cam
    cam_coords = intrinsics_inv.bmm(current_pixel_coords).view(b, 3, h, w)
RuntimeError: invalid argument 7: equal number of batches expected at /.../THC/generic/THCTensorMathBlas.cu:471

I'm not exactly sure what batch numbers have to be the same. Also, the problem seems to get fixed by changing the number of images in the training and validation datasets, which suggests that perhaps both the number of training and testing images have to be divisible by the batch size or something similar. Do you have an idea what's going on? Thanks!

**Comment by ClementPinard** [comment]
Hi, thanks for using my code !

The error here is triggered by batch matrix multiplication.
`Intrinsics_inv` is supposed to be of size `Bx3x3`, and `current_pixel_coords` is supposed to be of size `Bx3xN`, you are free about the `N`, it can be anything (here it is `h*w`) but both batch sizes (`B`) must be the same. The problem seems to come from a wrong size in on of these two tensors, you might want to check their sizes thoroughly just before calling the function `bmm`

Clément

**Comment by marianlonga** [comment]
Thanks! Yes, there was indeed a problem with my code with different batch sizes for `intrinsics_inv` and `current_pixel_coords`, now it's working
