### ISSUE TITLE
Why are small batches of size 4 used?

### ISSUE THREAD

**Issue by ethancaballero** [ClementPinard/SfmLearner-Pytorch#4]
That seems like a small batch size. Why are size 4 batches used during training?

**Comment by ClementPinard** [comment]
For the sake of reproducibility. Original paper did use batch size of 4: https://github.com/tinghuiz/SfMLearner

It may be because of low gpu capabilities of the machine it has been initially worked on.

More generally, it is considered better to keep a batch size not too high, so as long as you use all your GPU capabilities (which I do), you're better off than with a higher batch size.

Anyway you can try a higher batchsize (even with multi gpu) and see for yourself !
