### ISSUE TITLE
Confusion about PoseNet architecture

### ISSUE THREAD

**Issue by niujinshuchong** [ClementPinard/SfmLearner-Pytorch#51]
Hi, thank you for this work!
I am confused wih the network architecture of PoseNet. In PoseNet, you concat target image and all the reference images (2 or 4 images) together (https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/models/PoseExpNet.py#L28) and predict relative pose for every of these reference images. 
Actually we want to estimate relative pose between two frames. So in my opinion, taking every two frames as input in PoseNet may be more reasonable. Have you try these? Why design PoseNet in such a way?

**Comment by ClementPinard** [comment]
short answer, because the original author did so

Long answer, we don't want the relative pose between two, but between target frame and each reference frame. We could indeed do a network that takes two frames into input the target frame and one reference, and do that for every reference frame, but that means the pose network only have temporal context of two frames. The fact that all the frames in the sample are temporally close to each other would not be leveraged.

The take away point is that computing pose of a whole sequence of frames is deemed easier than pose of simple pair.
Now you can probably argue that "2frames" pose networks are not that and some papers tend to agree with this http://openaccess.thecvf.com/content_cvpr_2018/html/Mahjourian_Unsupervised_Learning_of_CVPR_2018_paper.html but the point of this repo is to provide a consistent baseline reproducing with fidelity the original tensorflow code from the author https://github.com/tinghuiz/SfMLearner

**Comment by niujinshuchong** [comment]
@ClementPinard Thanks for your kind answer.
