### ISSUE TITLE
Inference on a different self-driving dataset 

### ISSUE THREAD

**Issue by karttikeya** [ClementPinard/SfmLearner-Pytorch#65]
Hi Clement,

Thank you very much for your implementation. I am looking to use a pretrained model for egomotion detection from egocentric videos and found the SfMLearner implementation. After a bit of browsing, it looks like it is possible to use it on the dataset I'm interested in ([JAAD](http://data.nvision2.eecs.yorku.ca/JAAD_dataset/)) since JAAD only has video frame labelled with pedestrian bb ie. no camera calibration matrices etc. (which rules out approaches like ORB-SLAM). However, I'm unsure whether i'm right and also how to pre-process the dataset to use your provided posenet model for inference. I would appreciate your views on this! 

Thanks!

**Comment by ClementPinard** [comment]
Hello, thank for your interest in this repo !

You actually need calibration matrix in order to estimate the target frame from the reference frames. So I'm afraid JAAD info won't be enough.
Also, it seems that JAAD has fish-eye camera, or at least with some distortion, while it's also needed for SFMLearner to have perfectly rectified frames.
And finally, SFMLearner unfortunately only works for rigid scenes, which is not the case with pedestrians.

All in all, the mandatory aspect of a dataset is to be able to deduce the optical flow of a static frame from depth and displacement : frames don't necessary need to be rectified, but you need at least a proper calibration.

**Comment by karttikeya** [comment]
I see. Thanks for the information. Since it seems like rectified frames are not necessary and assuming pedestrians are not a big part of the scene or there are other rigid objects for good enough optical flow estimation the main issue is with Camera Calibration matrix. I was planning to side step in the following fashion:

Map the 3D coordinates to reference frame using the estimated rotation matrix and then use a linear layer (of 3 neurons only) to project the 3D coordinated into the image space. Then train this linear layer along with rest of the downstream mode in an end to end fashion hoping that the linear layer in front will learn to encode the necessary information. 
I realize this is not tangent to this repo but since you've been working with ideas around this, I would appreciate your gut feeling on this. Thanks!

**Comment by ClementPinard** [comment]
I'm not sure how you plan to go from image+depth to 3D points since you don't have the calibration (which is composed by an intrinsic matrix by also some distortion coefficients)

Estimating the plane /world transformation (direct and inverse, it's important to get both)  can be a good idea, but it's going to be hard with a monocular camera to which we don't know pose. Maybe with stereo frames or qith a perfectly known pose it could work though

**Comment by karttikeya** [comment]
I see. Thanks for the feedback.
