### ISSUE TITLE
predictions.npy

### ISSUE THREAD

**Issue by danbo2** [ClementPinard/SfmLearner-Pytorch#78]
Hi @ClementPinard ,

I am curious about the file predictions.npy. what is the data structure of this file ? How it is generated ? from training process ?

Thanks,
Yiyi

**Comment by danbo2** [comment]
The first problem has been solved through reading code details. But I meet another issue. 
![pose](https://user-images.githubusercontent.com/16380245/69010503-7d169900-092e-11ea-8412-dbcebeef8646.PNG) I find the seq_length is only 1, and the nb_ref_images = 0 in the source code.
![length](https://user-images.githubusercontent.com/16380245/69010527-b949f980-092e-11ea-975b-ad00b488ea97.PNG)

**Comment by danbo2** [comment]
I think the result of prediction.npy is in 5-pose snippet format. Is this in world coordinate or camera coordinate ? How can I merge them to one single full camera motion ?

**Comment by danbo2** [comment]
BTW, for training dataset, 
![data](https://user-images.githubusercontent.com/16380245/69018339-e5d73300-0979-11ea-80e7-f67b694e52b1.PNG)
Is calibration information used for training ?

**Comment by ClementPinard** [comment]
Are you talking about the predictions.npy in the drive folder containing the pretrained nets ?
In that case, the predictions were obtained using the pretrained dispnet with the test_disp script
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/test_disp.py

the key idea is that the predictions are up to a factor, and thus you can either get the right scale factor from the depth groundtruth or from the displacement magnitude groundtruth.

In the second case you will need a PoseNet to estimate the displacement, and thus you can multiply the output of dispnet with a ratio between posenet output and actual displacement. It is extremely important that you use the same PoseNet that was trained with the very DispNet you want to test. The PoseNet network provided in the drive folder was not trained the same time as the DispNet, don't use it for evaluation ! The official evaluation does not use PoseNet anyway...

Also, as you pointed it out, PoseNet can not have only a seq of more than 1 (otherwise no displacement is estimated since you only have 1 image). But I suspect you played around with the code because normally [this code section](https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/test_disp.py#L48-L56) from the test script wouldn't let you have a both PoseNet defined and `seq_length` set to 1

**Comment by danbo2** [comment]
I think the seq_length is 1 as well, when I loaded the pre-trained model you gave in Google drive and I used test_pose.py script.

Thanks,
Yiyi
