### ISSUE TITLE
cam2pixel of inverse_warp  parameter

### ISSUE THREAD

**Issue by TimingSpace** [ClementPinard/SfmLearner-Pytorch#90]
there seems to be a small buy in `inverse_warp.py line 43`
`def cam2pixel(cam_coords, proj_c2p_rot, proj_c2p_tr, padding_mode):`

Why is there a ` padding_mode` parameter?

**Comment by ClementPinard** [comment]
Hi thanks for noticing it.

This is due to the fact that before I defines the "zero" padding as if a point is outside frame, make it very far so that the resulting color is not an interpolation between a valid pixel and zeroed one.

Since then, I changed it to take care of it here : https://github.com/ClementPinard/SfmLearner-Pytorch/blob/e1b5b0de40fe212f7ba8807e3037fedd0fe4f12f/inverse_warp.py#L186 , we construct a boolean array that tells us on what pixel we apply the photometric loss.

I'll change the function definition soon.

**Comment by ClementPinard** [comment]
Solves with last commit
