### ISSUE TITLE
grid_sample issue in inverse_warp.py

### ISSUE THREAD

**Issue by KeyaoLi10** [ClementPinard/SfmLearner-Pytorch#92]
pytorch < 1.3 does not have the attribute 'align_corners' for torch.nn.functional.grid_sample() , without dropping it will raise error

**Comment by ClementPinard** [comment]
Yes, but this option is needed for pytorch > 1.4 because the default behaviour is not working anymore, I introduces border effect on interpolation that prevents the whole thing from converging. The only advice I can give you is either update pytorch or remove this option, either by yourself or revert the last commit. I can make a tag to indicate which commit you should pick for pytorch 1.3
